<BadInputScreen>:
    id: BadInputScreen
    BoxLayout:
        orientation:"vertical"
        MDLabel:
            text:'CANNOT CALCULATE! BAD INPUT!'
            halign:"center"
            theme_text_color:"Error"

        MDFillRoundFlatButton:
            text: 'OK'
            pos_hint: {"center_x": .5}
            md_bg_color:1,0,0,1
            on_release: root.change_screen_back()
        Widget:
            size_hint_y:0.8


