
<MenuScreen>:
    id: MenuScreen
    on_pre_leave: root.load_workouts
    BoxLayout:
        orientation:"vertical"
        padding:2
        GridLayout:
            cols:3
            padding:20
            pos_hint:{"top":1}
            MDLabel:
                id: calorie_label
                text: root.calorie_displayed
                halign:"center"
                theme_text_color:"Custom"
                text_color:app.theme_cls.primary_color
            MDTextFieldRound:
                id: calorie_input
                text: ''
                size_hint_x:0.6
                on_double_tap: self.text = ""
            BoxLayout:
                id: calorie
                orientation: "horizontal"
                size_hint_x:0.5
                MDTextButton:
                    text: "+"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H6"
                    on_release: root.on_plus_button_press(self.parent)
                MDTextButton:
                    text: "-"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H3"
                    on_release: root.on_minus_button_press(self.parent)

            MDLabel:
                id: carb_label
                halign:"center"
                text: root.carb_displayed
                theme_text_color:"Custom"
                text_color:app.theme_cls.primary_color
            MDTextFieldRound:
                id: carb_input
                text: ''
                size_hint_x:0.6
                on_double_tap: self.text = ""
            BoxLayout:
                id: carb
                orientation: "horizontal"
                size_hint_x:0.5
                MDTextButton:
                    text: "+"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H6"
                    on_release: root.on_plus_button_press(self.parent)
                MDTextButton:
                    text: "-"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H3"
                    on_release: root.on_minus_button_press(self.parent)

            MDLabel:
                id: fat_label
                halign:"center"
                text: root.fat_displayed
                theme_text_color:"Custom"
                text_color:app.theme_cls.primary_color
            MDTextFieldRound:
                id: fat_input
                text: ''
                size_hint_x:0.6
                on_double_tap: self.text = ""
            BoxLayout:
                id: fat
                orientation: "horizontal"
                size_hint_x:0.5
                MDTextButton:
                    text: "+"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H6"
                    on_release: root.on_plus_button_press(self.parent)
                MDTextButton:
                    text: "-"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H3"
                    on_release: root.on_minus_button_press(self.parent)

            MDLabel:
                id: protein_label
                text: root.protein_displayed
                halign:"center"
                theme_text_color:"Custom"
                text_color:app.theme_cls.primary_color
            MDTextFieldRound:
                id: protein_input
                text: ''
                size_hint_x:0.6
                on_double_tap: self.text = ""
            BoxLayout:
                id: protein
                orientation: "horizontal"
                size_hint_x:0.5
                MDTextButton:
                    text: "+"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H6"
                    on_release: root.on_plus_button_press(self.parent)
                MDTextButton:
                    text: "-"
                    size_hint:1,1
                    theme_text_color:"Custom"
                    text_color:app.theme_cls.primary_color
                    font_style:"H3"
                    on_release: root.on_minus_button_press(self.parent)
        GridLayout:
            cols:3
            spacing:3
            size_hint_y:0.3
            MDRaisedButton:
                text: 'Reset Intake'
                size_hint:1,1
                font_style:"Overline"
                md_bg_color: 1, 0, 0, 0.8
                on_press: root.on_reset_intake_button_press()
            MDRaisedButton:
                text: 'Tutorials'
                size_hint:1,1
                font_style:"Overline"
                on_press: root.on_video_links_button_press()
            MDRaisedButton:
                text: 'Workout Editor'
                size_hint:1,1
                font_style:"Overline"
                on_press: root.on_workout_editor_button_press()
            MDRaisedButton:
                text: 'Nutrition plan'
                size_hint:1,1
                font_style:"Overline"
                on_press: root.on_calorie_calculator_button_press()
            MDRaisedButton:
                text: 'Nutriments'
                size_hint:1,1
                font_style:"Overline"
                on_press: root.on_nutriments_button_press()
            MDRaisedButton:
                text: 'Healthy Recipes'
                size_hint:1,1
                font_style:"Overline"
                on_press: root.on_healthy_recipes_button_press()